/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/workbench/archive": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Archive */
        readonly post: operations["archive_workbench_recommendation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/workbench/recommendation": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Recommend */
        readonly post: operations["review_workbench_recommendation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/workbench/structure": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Inspect Structure */
        readonly post: operations["inspect_workbench_structure"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/codes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Codes */
        readonly get: operations["codes_codes_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/compute": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Compute */
        readonly post: operations["compute_compute_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/generate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Generate */
        readonly post: operations["generate_generate_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health */
        readonly get: operations["health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/models": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Models */
        readonly get: operations["models_models_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Ready */
        readonly get: operations["ready_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/recommend": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Recommend */
        readonly post: operations["recommend_recommend_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tasks": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Tasks */
        readonly get: operations["tasks_tasks_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchiveRequest */
        readonly ArchiveRequest: {
            /** @default {} */
            readonly hints: components["schemas"]["HintsResponse"];
            /**
             * @default {
             *       "code": "quantum_espresso",
             *       "functional": "PBEsol",
             *       "pseudo_accuracy": "efficiency",
             *       "task": "scf_single_point"
             *     }
             */
            readonly intent: components["schemas"]["IntentResponse"];
            /** Pseudo Table Id */
            readonly pseudo_table_id?: string | null;
            /** Review Digest */
            readonly review_digest: string;
            readonly source: components["schemas"]["StructureSourceRequest"];
        };
        /** CalculationDefaults */
        readonly CalculationDefaults: {
            readonly hints: components["schemas"]["HintsResponse"];
            readonly intent: components["schemas"]["IntentResponse"];
        };
        /** GeneratedFileResponse */
        readonly GeneratedFileResponse: {
            /** Content */
            readonly content: string;
            /** Path */
            readonly path: string;
            /** Role */
            readonly role: string;
            /** Sha256 */
            readonly sha256: string;
        };
        /** GuidedRequest */
        readonly GuidedRequest: {
            /** @default {} */
            readonly hints: components["schemas"]["HintsResponse"];
            /**
             * @default {
             *       "code": "quantum_espresso",
             *       "functional": "PBEsol",
             *       "pseudo_accuracy": "efficiency",
             *       "task": "scf_single_point"
             *     }
             */
            readonly intent: components["schemas"]["IntentResponse"];
            /** Pseudo Table Id */
            readonly pseudo_table_id?: string | null;
            readonly source: components["schemas"]["StructureSourceRequest"];
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** HintsResponse */
        readonly HintsResponse: {
            /** Conv Thr */
            readonly conv_thr?: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep?: number | null;
            /** K Grid */
            readonly k_grid?: readonly [
                number,
                number,
                number
            ] | null;
            /** K Spacing */
            readonly k_spacing?: number | null;
            /** Mixing Beta */
            readonly mixing_beta?: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy?: ("efficiency" | "precision") | null;
            /** Pseudo Type */
            readonly pseudo_type?: string | null;
            /** Relativistic Mode */
            readonly relativistic_mode?: string | null;
            /** Smearing Type */
            readonly smearing_type?: string | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry?: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling?: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized?: boolean | null;
            /** Use Vdw */
            readonly use_vdw?: boolean | null;
            /** Vdw Method */
            readonly vdw_method?: string | null;
        };
        /** IntentResponse */
        readonly IntentResponse: {
            /**
             * Code
             * @default quantum_espresso
             */
            readonly code: string;
            /**
             * Functional
             * @default PBEsol
             */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @default efficiency
             * @enum {string}
             */
            readonly pseudo_accuracy: "efficiency" | "precision";
            /**
             * Task
             * @default scf_single_point
             */
            readonly task: string;
        };
        readonly JsonValue: unknown;
        /** LatticeResponse */
        readonly LatticeResponse: {
            /** Angles Degrees */
            readonly angles_degrees: readonly [
                number,
                number,
                number
            ];
            /** Lengths Angstrom */
            readonly lengths_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Vectors Angstrom */
            readonly vectors_angstrom: readonly [
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ]
            ];
            /** Volume Angstrom3 */
            readonly volume_angstrom3: number;
        };
        /** PseudoSelectionResponse */
        readonly PseudoSelectionResponse: {
            /** Files */
            readonly files: readonly components["schemas"]["SelectedPseudoResponse"][];
            readonly table: components["schemas"]["PseudoTableResponse"];
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** PseudoTableResponse */
        readonly PseudoTableResponse: {
            /**
             * Accuracy
             * @enum {string}
             */
            readonly accuracy: "efficiency" | "precision";
            /** Citation */
            readonly citation: string;
            /** Default */
            readonly default: boolean;
            /** Elements */
            readonly elements: readonly string[];
            /** Functional */
            readonly functional: string;
            /** Id */
            readonly id: string;
            /** Licence */
            readonly licence: string;
            /** Provider */
            readonly provider: string;
            /** Relativistic */
            readonly relativistic: string;
            /** Upstream Table */
            readonly upstream_table: string;
            /** Version */
            readonly version: string;
        };
        /** RecommendationResponse */
        readonly RecommendationResponse: {
            /** Canonical Cif */
            readonly canonical_cif: string;
            /** Generated Files */
            readonly generated_files: readonly components["schemas"]["GeneratedFileResponse"][];
            readonly hints: components["schemas"]["HintsResponse"];
            readonly intent: components["schemas"]["IntentResponse"];
            /** Records */
            readonly records: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            };
            /** Review Digest */
            readonly review_digest: string;
            /** Schema Version */
            readonly schema_version: number;
            readonly selection: components["schemas"]["PseudoSelectionResponse"];
            readonly structure: components["schemas"]["StructureResponse"];
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** SelectedPseudoResponse */
        readonly SelectedPseudoResponse: {
            /** Ecutrho Ry */
            readonly ecutrho_ry: number | null;
            /** Ecutwfc Ry */
            readonly ecutwfc_ry: number | null;
            /** Element */
            readonly element: string;
            /** Filename */
            readonly filename: string;
            /** Functional */
            readonly functional: string | null;
            /** Provenance */
            readonly provenance: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            };
            /** Sha256 */
            readonly sha256: string;
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** SiteDocument */
        readonly SiteDocument: {
            /** Cartesian Coordinates Angstrom */
            readonly cartesian_coordinates_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Fractional Coordinates */
            readonly fractional_coordinates: readonly [
                number,
                number,
                number
            ];
            /** Species */
            readonly species: readonly components["schemas"]["SpeciesDocument"][];
        };
        /** SourceDocument */
        readonly SourceDocument: {
            /** Format */
            readonly format: string;
            /** Name */
            readonly name: string;
            /** Sha256 */
            readonly sha256: string;
            /** Size Bytes */
            readonly size_bytes: number;
        };
        /** SpeciesDocument */
        readonly SpeciesDocument: {
            /** Label */
            readonly label: string;
            /** Occupancy */
            readonly occupancy: number;
            /** Oxidation State */
            readonly oxidation_state?: number | null;
            /** Symbol */
            readonly symbol: string;
        };
        /** StructureInspectionRequest */
        readonly StructureInspectionRequest: {
            readonly source: components["schemas"]["StructureSourceRequest"];
        };
        /** StructureInspectionResponse */
        readonly StructureInspectionResponse: {
            /** Canonical Cif */
            readonly canonical_cif: string;
            readonly defaults: components["schemas"]["CalculationDefaults"];
            /** Pseudo Tables */
            readonly pseudo_tables: readonly components["schemas"]["PseudoTableResponse"][];
            readonly structure: components["schemas"]["StructureResponse"];
        };
        /** StructureResponse */
        readonly StructureResponse: {
            /** Formula */
            readonly formula: string;
            readonly lattice: components["schemas"]["LatticeResponse"];
            /** Periodicity */
            readonly periodicity: readonly [
                boolean,
                boolean,
                boolean
            ];
            /** Reduced Formula */
            readonly reduced_formula: string;
            /** Schema Version */
            readonly schema_version: number;
            /** Site Count */
            readonly site_count: number;
            /** Sites */
            readonly sites: readonly components["schemas"]["SiteDocument"][];
            readonly source: components["schemas"]["SourceDocument"];
        };
        /** StructureSourceRequest */
        readonly StructureSourceRequest: {
            /** Content */
            readonly content: string;
            /** Format */
            readonly format?: ("cif" | "poscar") | null;
            /** Name */
            readonly name: string;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly archive_workbench_recommendation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly review_workbench_recommendation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["GuidedRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly inspect_workbench_structure: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StructureInspectionRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StructureInspectionResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly codes_codes_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
    readonly compute_compute_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly [key: string]: unknown;
                };
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly generate_generate_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly [key: string]: unknown;
                };
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly models_models_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
    readonly ready_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
    readonly recommend_recommend_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly [key: string]: unknown;
                };
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly tasks_tasks_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
}
