/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/capabilities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Capabilities */
        readonly get: operations["capabilities_capabilities_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/compute": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Compute */
        readonly post: operations["compute_compute_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health */
        readonly get: operations["health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/inspect": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Inspect */
        readonly post: operations["inspect_inspect_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Ready */
        readonly get: operations["ready_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalculationDraft */
        readonly CalculationDraft: {
            readonly hints?: components["schemas"]["CalculationHints-Input"] | null;
            readonly intent?: components["schemas"]["CalculationIntent-Input"] | null;
            /** Pseudo Table */
            readonly pseudo_table?: string | null;
            readonly structure: components["schemas"]["InlineStructureSource"];
        };
        /** CalculationHints */
        readonly "CalculationHints-Input": {
            /** Conv Thr */
            readonly conv_thr?: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep?: number | null;
            /** K Grid */
            readonly k_grid?: readonly number[] | null;
            /** K Spacing */
            readonly k_spacing?: number | null;
            /** Mixing Beta */
            readonly mixing_beta?: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy?: string | null;
            /** Pseudo Type */
            readonly pseudo_type?: string | null;
            /** Relativistic Mode */
            readonly relativistic_mode?: string | null;
            /** Smearing Type */
            readonly smearing_type?: string | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry?: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling?: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized?: boolean | null;
            /** Use Vdw */
            readonly use_vdw?: boolean | null;
            /** Vdw Method */
            readonly vdw_method?: string | null;
        };
        /**
         * CalculationHints
         * @description Optional operator overrides. ``None`` means let Core decide.
         *     Non-None records ``user_hint`` provenance. Partial overrides supported.
         *     Units: ``k_spacing`` in Å⁻¹ (VASP KSPACING),
         *     ``smearing_width_ry`` and ``conv_thr`` in Rydberg.
         */
        readonly "CalculationHints-Output": {
            /** Conv Thr */
            readonly conv_thr?: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep?: number | null;
            /** K Grid */
            readonly k_grid?: readonly [
                number,
                number,
                number
            ] | null;
            /** K Spacing */
            readonly k_spacing?: number | null;
            /** Mixing Beta */
            readonly mixing_beta?: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy?: ("efficiency" | "precision") | null;
            /** Pseudo Type */
            readonly pseudo_type?: string | null;
            /** Relativistic Mode */
            readonly relativistic_mode?: string | null;
            /** Smearing Type */
            readonly smearing_type?: string | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry?: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling?: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized?: boolean | null;
            /** Use Vdw */
            readonly use_vdw?: boolean | null;
            /** Vdw Method */
            readonly vdw_method?: ("d3" | "d3bj" | "ts" | "mbd") | null;
        };
        /** CalculationIntent */
        readonly "CalculationIntent-Input": {
            /**
             * Code
             * @default quantum_espresso
             */
            readonly code: string;
            /**
             * Functional
             * @default PBEsol
             */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @default efficiency
             */
            readonly pseudo_accuracy: string;
            /**
             * Task
             * @default scf_single_point
             */
            readonly task: string;
        };
        /** CalculationIntent */
        readonly "CalculationIntent-Output": {
            /**
             * Code
             * @default quantum_espresso
             */
            readonly code: string;
            /**
             * Functional
             * @default PBEsol
             */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @default efficiency
             * @enum {string}
             */
            readonly pseudo_accuracy: "efficiency" | "precision";
            /**
             * Task
             * @default scf_single_point
             */
            readonly task: string;
        };
        /** CalculationTaskCapability */
        readonly CalculationTaskCapability: {
            /** Description */
            readonly description: string;
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Presets */
            readonly presets: readonly components["schemas"]["PresetCapability"][];
            /** Revision */
            readonly revision: string;
            /** Selectable Record Ids */
            readonly selectable_record_ids: readonly string[];
            /** Stages */
            readonly stages: readonly components["schemas"]["StageCapability"][];
        };
        /** Capabilities */
        readonly Capabilities: {
            /** Core Version */
            readonly core_version: string;
            readonly default_hints: components["schemas"]["CalculationHints-Output"];
            readonly default_intent: components["schemas"]["CalculationIntent-Output"];
            /** Models */
            readonly models: readonly components["schemas"]["ModelCapability"][];
            /** Pseudopotential Sets */
            readonly pseudopotential_sets: readonly components["schemas"]["PseudopotentialSetCapability"][];
            /** Target Codes */
            readonly target_codes: readonly string[];
            /** Tasks */
            readonly tasks: readonly components["schemas"]["CalculationTaskCapability"][];
        };
        /** ComputationResult */
        readonly ComputationResult: {
            /** Draft */
            readonly draft: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            };
            readonly publication: components["schemas"]["Publication"] | null;
            /** Records */
            readonly records: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Schema Version
             * @constant
             */
            readonly schema_version: 1;
            /** Selection */
            readonly selection: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            };
            /** Task */
            readonly task: string;
            /** Task Revision */
            readonly task_revision: string;
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** ComputeRequest */
        readonly ComputeRequest: {
            readonly draft: components["schemas"]["CalculationDraft"];
            /** Output */
            readonly output: components["schemas"]["MemoryOutput"] | components["schemas"]["HttpArchiveOutput"];
            readonly selection: components["schemas"]["SelectionDocument"];
        };
        /** Error */
        readonly Error: {
            /** Asset Id */
            readonly asset_id?: string | null;
            /** Details */
            readonly details?: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Kind */
            readonly kind: string;
            /** Message */
            readonly message: string;
            /** Retryable */
            readonly retryable?: boolean | null;
            /** Root */
            readonly root?: string | null;
            /** Version */
            readonly version?: string | null;
        };
        /** ErrorResponse */
        readonly ErrorResponse: {
            readonly error: components["schemas"]["Error"];
        };
        /** HttpArchiveOutput */
        readonly HttpArchiveOutput: {
            /**
             * Kind
             * @constant
             */
            readonly kind: "archive";
        };
        /** InlineStructureSource */
        readonly InlineStructureSource: {
            /** Content */
            readonly content: string;
            /** Format */
            readonly format?: ("cif" | "poscar") | null;
            /**
             * Kind
             * @default inline
             * @constant
             */
            readonly kind: "inline";
            /** Name */
            readonly name: string;
        };
        readonly JsonValue: unknown;
        /** LatticeDocument */
        readonly LatticeDocument: {
            /** Angles Degrees */
            readonly angles_degrees: readonly [
                number,
                number,
                number
            ];
            /** Lengths Angstrom */
            readonly lengths_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Vectors Angstrom */
            readonly vectors_angstrom: readonly [
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ]
            ];
            /** Volume Angstrom3 */
            readonly volume_angstrom3: number;
        };
        /** MemoryOutput */
        readonly MemoryOutput: {
            /**
             * Kind
             * @constant
             */
            readonly kind: "memory";
        };
        /** ModelCapability */
        readonly ModelCapability: {
            /** Feature Set */
            readonly feature_set: string;
            /** Id */
            readonly id: string;
            /** Model Type */
            readonly model_type: string;
            /** Name */
            readonly name: string;
            /** Revision */
            readonly revision: string | null;
            /** Role */
            readonly role: string;
            /** Source */
            readonly source: string;
            /** Target */
            readonly target: string;
            /** Version */
            readonly version: string;
        };
        /** PresetCapability */
        readonly PresetCapability: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Output Record Ids */
            readonly output_record_ids: readonly string[];
        };
        /** PresetSelection */
        readonly PresetSelection: {
            /** Preset */
            readonly preset: string;
        };
        /** PseudopotentialSetCapability */
        readonly PseudopotentialSetCapability: {
            /** Accuracy */
            readonly accuracy: string;
            /** Citation */
            readonly citation: string;
            /** Default */
            readonly default: boolean;
            /** Functional */
            readonly functional: string;
            /** Id */
            readonly id: string;
            /** Licence */
            readonly licence: string;
            /** Provider */
            readonly provider: string;
            /** Relativistic Treatment */
            readonly relativistic_treatment: string;
            /** Supported Elements */
            readonly supported_elements: readonly string[];
            /** Upstream Name */
            readonly upstream_name: string;
            /** Version */
            readonly version: string;
        };
        /** Publication */
        readonly Publication: {
            /** Files */
            readonly files: readonly string[];
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "directory" | "archive";
            /** Manifest Sha256 */
            readonly manifest_sha256: string;
            /** Output Sha256 */
            readonly output_sha256?: string | null;
            /** Path */
            readonly path: string;
        };
        /** RecordSelection */
        readonly RecordSelection: {
            /** Records */
            readonly records: readonly ("analysis" | "advice" | "k_points" | "selection" | "generated_files" | "dft_input_data")[];
        };
        readonly SelectionDocument: components["schemas"]["PresetSelection"] | components["schemas"]["RecordSelection"];
        /** SpeciesOccupancy */
        readonly SpeciesOccupancy: {
            /** Label */
            readonly label: string;
            /** Occupancy */
            readonly occupancy: number;
            /** Oxidation State */
            readonly oxidation_state?: number | null;
            /** Symbol */
            readonly symbol: string;
        };
        /** StageCapability */
        readonly StageCapability: {
            /** Description */
            readonly description: string;
            /** Id */
            readonly id: string;
            /** Input Record Ids */
            readonly input_record_ids: readonly string[];
            /** Name */
            readonly name: string;
            /** Output Record Id */
            readonly output_record_id: string;
        };
        /** StructureDocument */
        readonly StructureDocument: {
            /** Formula */
            readonly formula: string;
            readonly lattice: components["schemas"]["LatticeDocument"];
            /** Periodicity */
            readonly periodicity: readonly [
                boolean,
                boolean,
                boolean
            ];
            /** Reduced Formula */
            readonly reduced_formula: string;
            /** Schema Version */
            readonly schema_version: number;
            /** Site Count */
            readonly site_count: number;
            /** Sites */
            readonly sites: readonly components["schemas"]["StructureSiteDocument"][];
        };
        /** StructureInspection */
        readonly StructureInspection: {
            /** Canonical Cif */
            readonly canonical_cif: string;
            /**
             * Schema Version
             * @default 1
             */
            readonly schema_version: number;
            readonly source: components["schemas"]["StructureSourceDocument"];
            readonly structure: components["schemas"]["StructureDocument"];
        };
        /** StructureInspectionRequest */
        readonly StructureInspectionRequest: {
            readonly source: components["schemas"]["InlineStructureSource"];
        };
        /** StructureSiteDocument */
        readonly StructureSiteDocument: {
            /** Cartesian Coordinates Angstrom */
            readonly cartesian_coordinates_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Fractional Coordinates */
            readonly fractional_coordinates: readonly [
                number,
                number,
                number
            ];
            /** Species */
            readonly species: readonly components["schemas"]["SpeciesOccupancy"][];
        };
        /** StructureSourceDocument */
        readonly StructureSourceDocument: {
            /** Content */
            readonly content: string | null;
            /** Format */
            readonly format: string;
            /** Name */
            readonly name: string;
            /**
             * Origin
             * @enum {string}
             */
            readonly origin: "inline" | "path" | "generated";
            /** Sha256 */
            readonly sha256: string | null;
            /** Size Bytes */
            readonly size_bytes: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly capabilities_capabilities_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    readonly compute_compute_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ComputeRequest"];
            };
        };
        readonly responses: {
            /** @description Canonical Computation Result JSON or an in-memory ZIP archive. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ComputationResult"];
                    readonly "application/zip": string;
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Failed Dependency */
            readonly 424: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            readonly 503: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly inspect_inspect_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StructureInspectionRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StructureInspection"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly ready_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
}
