/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/capabilities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Capabilities */
        readonly get: operations["capabilities_capabilities_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/compute": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Compute */
        readonly post: operations["compute_compute_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health */
        readonly get: operations["health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/inspect": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Inspect */
        readonly post: operations["inspect_inspect_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Ready */
        readonly get: operations["ready_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalculationDraft */
        readonly CalculationDraft: {
            readonly hints?: components["schemas"]["CalculationHints-Input"] | null;
            readonly intent?: components["schemas"]["CalculationIntent-Input"] | null;
            /** Pseudo Table */
            readonly pseudo_table?: string | null;
            readonly structure: components["schemas"]["InlineStructureSource"];
        };
        /** CalculationHints */
        readonly "CalculationHints-Input": {
            /** Conv Thr */
            readonly conv_thr?: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep?: number | null;
            /** K Grid */
            readonly k_grid?: readonly number[] | null;
            /** K Spacing */
            readonly k_spacing?: number | null;
            /** Mixing Beta */
            readonly mixing_beta?: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy?: ("efficiency" | "precision") | null;
            /** Pseudo Type */
            readonly pseudo_type?: ("NC" | "USPP" | "PAW") | null;
            /** Relativistic Mode */
            readonly relativistic_mode?: ("scalar" | "full" | "non-relativistic") | null;
            /** Smearing Type */
            readonly smearing_type?: ("fixed" | "gaussian" | "mp" | "cold") | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry?: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling?: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized?: boolean | null;
            /** Use Vdw */
            readonly use_vdw?: boolean | null;
            /** Vdw Method */
            readonly vdw_method?: ("d3" | "d3bj" | "ts" | "mbd") | null;
        };
        /**
         * CalculationHints
         * @description Optional operator overrides. ``None`` means let Core decide.
         *     Non-None records ``user_hint`` provenance. Partial overrides supported.
         *     Units: ``k_spacing`` in Å⁻¹ (VASP KSPACING),
         *     ``smearing_width_ry`` and ``conv_thr`` in Rydberg.
         */
        readonly "CalculationHints-Output": {
            /** Conv Thr */
            readonly conv_thr?: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep?: number | null;
            /** K Grid */
            readonly k_grid?: readonly [
                number,
                number,
                number
            ] | null;
            /** K Spacing */
            readonly k_spacing?: number | null;
            /** Mixing Beta */
            readonly mixing_beta?: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy?: ("efficiency" | "precision") | null;
            /** Pseudo Type */
            readonly pseudo_type?: ("NC" | "USPP" | "PAW") | null;
            /** Relativistic Mode */
            readonly relativistic_mode?: ("scalar" | "full" | "non-relativistic") | null;
            /** Smearing Type */
            readonly smearing_type?: ("fixed" | "gaussian" | "mp" | "cold") | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry?: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling?: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized?: boolean | null;
            /** Use Vdw */
            readonly use_vdw?: boolean | null;
            /** Vdw Method */
            readonly vdw_method?: ("d3" | "d3bj" | "ts" | "mbd") | null;
        };
        /** CalculationIntent */
        readonly "CalculationIntent-Input": {
            /**
             * Code
             * @default quantum_espresso
             */
            readonly code: string;
            /**
             * Functional
             * @default PBEsol
             */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @default efficiency
             * @enum {string}
             */
            readonly pseudo_accuracy: "efficiency" | "precision";
            /**
             * Task
             * @default scf_single_point
             */
            readonly task: string;
        };
        /** CalculationIntent */
        readonly "CalculationIntent-Output": {
            /**
             * Code
             * @default quantum_espresso
             */
            readonly code: string;
            /**
             * Functional
             * @default PBEsol
             */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @default efficiency
             * @enum {string}
             */
            readonly pseudo_accuracy: "efficiency" | "precision";
            /**
             * Task
             * @default scf_single_point
             */
            readonly task: string;
        };
        /** CalculationTaskCapability */
        readonly CalculationTaskCapability: {
            /** Description */
            readonly description: string;
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Presets */
            readonly presets: readonly components["schemas"]["PresetCapability"][];
            /** Revision */
            readonly revision: string;
            /** Selectable Record Ids */
            readonly selectable_record_ids: readonly string[];
            /** Stages */
            readonly stages: readonly components["schemas"]["StageCapability"][];
        };
        /** Capabilities */
        readonly Capabilities: {
            /** Core Version */
            readonly core_version: string;
            readonly default_hints: components["schemas"]["CalculationHints-Output"];
            readonly default_intent: components["schemas"]["CalculationIntent-Output"];
            /** Models */
            readonly models: readonly components["schemas"]["ModelCapability"][];
            /** Pseudopotential Sets */
            readonly pseudopotential_sets: readonly components["schemas"]["PseudopotentialSetCapability"][];
            /** Target Codes */
            readonly target_codes: readonly string[];
            /** Tasks */
            readonly tasks: readonly components["schemas"]["CalculationTaskCapability"][];
        };
        /** ComputationResult */
        readonly ComputationResult: {
            readonly draft: components["schemas"]["SerializedCalculationDraft"];
            readonly publication: components["schemas"]["Publication"] | null;
            readonly records: components["schemas"]["Records"];
            /**
             * Schema Version
             * @constant
             */
            readonly schema_version: 1;
            readonly selection: components["schemas"]["SelectionDocument"];
            /** Task */
            readonly task: string;
            /** Task Revision */
            readonly task_revision: string;
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** ComputeRequest */
        readonly ComputeRequest: {
            readonly draft: components["schemas"]["CalculationDraft"];
            readonly selection: components["schemas"]["SelectionDocument"];
        };
        /** ConvergenceAdvice */
        readonly ConvergenceAdvice: {
            /** Conv Thr */
            readonly conv_thr: number;
            /** Electron Maxstep */
            readonly electron_maxstep: number;
            /** Mixing Beta */
            readonly mixing_beta: number;
            readonly provenance: components["schemas"]["Provenance"];
        };
        /** DftInputData */
        readonly DftInputData: {
            /** Artifacts */
            readonly artifacts: readonly components["schemas"]["SerializedInputArtifact"][];
            /** Citations */
            readonly citations: readonly string[];
            /** Manifest */
            readonly manifest: {
                readonly [key: string]: unknown;
            };
            readonly pseudopotential_set: components["schemas"]["PseudopotentialSetIdentity"];
            readonly runtime: components["schemas"]["SerializedRuntime"];
            /**
             * Schema Version
             * @constant
             */
            readonly schema_version: 1;
        };
        /** Error */
        readonly Error: {
            /** Asset Id */
            readonly asset_id?: string | null;
            /** Details */
            readonly details?: {
                readonly [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Kind */
            readonly kind: string;
            /** Message */
            readonly message: string;
            /** Reason */
            readonly reason?: string | null;
            /** Retryable */
            readonly retryable?: boolean | null;
            /** Version */
            readonly version?: string | null;
        };
        /** ErrorResponse */
        readonly ErrorResponse: {
            readonly error: components["schemas"]["Error"];
        };
        /** GeneratedArtifactSource */
        readonly GeneratedArtifactSource: {
            /** Identity */
            readonly identity: string;
            /**
             * Kind
             * @constant
             */
            readonly kind: "generated";
        };
        /** GeneratedFile */
        readonly GeneratedFile: {
            /** Content */
            readonly content: string;
            /** Path */
            readonly path: string;
            /** Role */
            readonly role: string;
        };
        /** InlineStructureSource */
        readonly InlineStructureSource: {
            /** Content */
            readonly content: string;
            /** Format */
            readonly format?: ("cif" | "poscar") | null;
            /**
             * Kind
             * @default inline
             * @constant
             */
            readonly kind: "inline";
            /** Name */
            readonly name: string;
        };
        /** InstalledArtifactSource */
        readonly InstalledArtifactSource: {
            /** Asset Id */
            readonly asset_id: string;
            /** Asset Version */
            readonly asset_version: string;
            /**
             * Kind
             * @constant
             */
            readonly kind: "installed";
            /** Path */
            readonly path: string;
            /** Preparation Fingerprint */
            readonly preparation_fingerprint: string;
        };
        readonly JsonValue: unknown;
        /** KPointSelection */
        readonly KPointSelection: {
            /** Grid */
            readonly grid: readonly [
                number,
                number,
                number
            ];
            /** Mesh Type */
            readonly mesh_type: string;
            readonly provenance: components["schemas"]["Provenance"];
            /** Shift */
            readonly shift: readonly [
                0 | 1,
                0 | 1,
                0 | 1
            ];
        };
        /** LatticeDocument */
        readonly LatticeDocument: {
            /** Angles Degrees */
            readonly angles_degrees: readonly [
                number,
                number,
                number
            ];
            /** Lengths Angstrom */
            readonly lengths_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Vectors Angstrom */
            readonly vectors_angstrom: readonly [
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ],
                readonly [
                    number,
                    number,
                    number
                ]
            ];
            /** Volume Angstrom3 */
            readonly volume_angstrom3: number;
        };
        /** LocalPseudoRoot */
        readonly LocalPseudoRoot: {
            /**
             * Kind
             * @constant
             */
            readonly kind: "local_root";
        };
        /** MagnetismAdvice */
        readonly MagnetismAdvice: {
            /** Magnetic Elements */
            readonly magnetic_elements: readonly string[];
            readonly provenance: components["schemas"]["Provenance"];
            /** Spin Polarized */
            readonly spin_polarized: boolean;
        };
        /** ModelCapability */
        readonly ModelCapability: {
            /** Feature Set */
            readonly feature_set: string;
            /** Id */
            readonly id: string;
            /** Model Type */
            readonly model_type: string;
            /** Name */
            readonly name: string;
            /** Revision */
            readonly revision: string | null;
            /** Role */
            readonly role: string;
            /** Source */
            readonly source: string;
            /** Target */
            readonly target: string;
            /** Version */
            readonly version: string;
        };
        /** ParameterAdvice */
        readonly ParameterAdvice: {
            readonly convergence: components["schemas"]["ConvergenceAdvice"];
            readonly magnetism: components["schemas"]["MagnetismAdvice"];
            readonly pseudopotential_requirements: components["schemas"]["PseudopotentialRequirements"];
            readonly smearing: components["schemas"]["SmearingAdvice"];
            readonly spin_orbit: components["schemas"]["SpinOrbitAdvice"];
            readonly vdw: components["schemas"]["VdwAdvice"];
        };
        /** PreparedComputation */
        readonly PreparedComputation: {
            /** Archive */
            readonly archive?: string | null;
            readonly result: components["schemas"]["ComputationResult"];
        };
        /** PresetCapability */
        readonly PresetCapability: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Output Record Ids */
            readonly output_record_ids: readonly string[];
        };
        /** PresetSelection */
        readonly PresetSelection: {
            /** Preset */
            readonly preset: string;
        };
        /** Provenance */
        readonly Provenance: {
            /** Confidence */
            readonly confidence: number | null;
            /** Data Source */
            readonly data_source: string | null;
            /** Details */
            readonly details: {
                readonly [key: string]: unknown;
            } | null;
            /** Reason */
            readonly reason: string;
            /**
             * Source
             * @enum {string}
             */
            readonly source: "analysis" | "user_hint" | "default" | "model" | "lookup" | "fallback";
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** PseudoCutoffs */
        readonly PseudoCutoffs: {
            /** Ecutrho Ry */
            readonly ecutrho_ry: number | null;
            /** Ecutwfc Ry */
            readonly ecutwfc_ry: number | null;
        };
        /** PseudopotentialRequirements */
        readonly PseudopotentialRequirements: {
            /**
             * Accuracy
             * @enum {string}
             */
            readonly accuracy: "efficiency" | "precision";
            /** Functional */
            readonly functional: string;
            readonly provenance: components["schemas"]["Provenance"];
            /** Pseudo Type */
            readonly pseudo_type: ("NC" | "USPP" | "PAW") | null;
            /**
             * Relativistic
             * @enum {string}
             */
            readonly relativistic: "scalar" | "full" | "non-relativistic";
        };
        /** PseudopotentialSetCapability */
        readonly PseudopotentialSetCapability: {
            /** Accuracy */
            readonly accuracy: string;
            /** Citation */
            readonly citation: string;
            /** Default */
            readonly default: boolean;
            /** Functional */
            readonly functional: string;
            /** Id */
            readonly id: string;
            /** Licence */
            readonly licence: string;
            /** Provider */
            readonly provider: string;
            /** Relativistic Treatment */
            readonly relativistic_treatment: string;
            /** Supported Elements */
            readonly supported_elements: readonly string[];
            /** Upstream Name */
            readonly upstream_name: string;
            /** Version */
            readonly version: string;
        };
        /** PseudopotentialSetIdentity */
        readonly PseudopotentialSetIdentity: {
            /** Accuracy */
            readonly accuracy: string;
            /** Citation */
            readonly citation: string;
            /** Functional */
            readonly functional: string;
            /** Id */
            readonly id: string;
            /** Licence */
            readonly licence: string;
            /** Policy */
            readonly policy: {
                readonly [key: string]: unknown;
            };
            /** Provider */
            readonly provider: string;
            /** Relativistic */
            readonly relativistic: string;
            /** Version */
            readonly version: string | null;
        };
        /** Publication */
        readonly Publication: {
            /** Files */
            readonly files: readonly string[];
            /**
             * Kind
             * @enum {string}
             */
            readonly kind: "directory" | "archive";
            /** Manifest Sha256 */
            readonly manifest_sha256: string;
            /** Output Sha256 */
            readonly output_sha256: string | null;
            /** Path */
            readonly path: string;
        };
        /** RecordSelection */
        readonly RecordSelection: {
            /** Records */
            readonly records: readonly string[];
        };
        /** Records */
        readonly Records: {
            readonly advice?: components["schemas"]["ParameterAdvice"];
            readonly analysis?: components["schemas"]["StructureAnalysisRecord"];
            readonly dft_input_data?: components["schemas"]["DftInputData"];
            /** Generated Files */
            readonly generated_files?: readonly components["schemas"]["GeneratedFile"][];
            readonly k_points?: components["schemas"]["KPointSelection"];
            readonly selection?: components["schemas"]["SelectionRecord"];
        };
        /** RuntimeAssetFile */
        readonly RuntimeAssetFile: {
            /** Path */
            readonly path: string;
            /** Role */
            readonly role: string;
            /** Sha256 */
            readonly sha256: string;
            /** Size Bytes */
            readonly size_bytes: number;
        };
        readonly SelectionDocument: components["schemas"]["PresetSelection"] | components["schemas"]["RecordSelection"];
        /** SelectionRecord */
        readonly SelectionRecord: {
            /** Pseudopotentials */
            readonly pseudopotentials: readonly components["schemas"]["SerializedPseudopotentialSelection"][];
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** SerializedCalculationDraft */
        readonly SerializedCalculationDraft: {
            readonly hints: components["schemas"]["SerializedCalculationHints"];
            readonly intent: components["schemas"]["SerializedCalculationIntent"];
            readonly kmesh_model: components["schemas"]["SerializedModel"] | null;
            /** Pseudo Metadata */
            readonly pseudo_metadata: readonly components["schemas"]["SerializedPseudoMetadata"][] | null;
            readonly pseudo_root: components["schemas"]["LocalPseudoRoot"] | null;
            /** Pseudo Table */
            readonly pseudo_table: string | null;
            readonly structure: components["schemas"]["StructureInspection"];
        };
        /** SerializedCalculationHints */
        readonly SerializedCalculationHints: {
            /** Conv Thr */
            readonly conv_thr: number | null;
            /** Electron Maxstep */
            readonly electron_maxstep: number | null;
            /** K Grid */
            readonly k_grid: readonly [
                number,
                number,
                number
            ] | null;
            /** K Spacing */
            readonly k_spacing: number | null;
            /** Mixing Beta */
            readonly mixing_beta: number | null;
            /** Pseudo Accuracy */
            readonly pseudo_accuracy: ("efficiency" | "precision") | null;
            /** Pseudo Type */
            readonly pseudo_type: ("NC" | "USPP" | "PAW") | null;
            /** Relativistic Mode */
            readonly relativistic_mode: ("scalar" | "full" | "non-relativistic") | null;
            /** Smearing Type */
            readonly smearing_type: ("fixed" | "gaussian" | "mp" | "cold") | null;
            /** Smearing Width Ry */
            readonly smearing_width_ry: number | null;
            /** Spin Orbit Coupling */
            readonly spin_orbit_coupling: boolean | null;
            /** Spin Polarized */
            readonly spin_polarized: boolean | null;
            /** Use Vdw */
            readonly use_vdw: boolean | null;
            /** Vdw Method */
            readonly vdw_method: ("d3" | "d3bj" | "ts" | "mbd") | null;
        };
        /** SerializedCalculationIntent */
        readonly SerializedCalculationIntent: {
            /** Code */
            readonly code: string;
            /** Functional */
            readonly functional: string;
            /**
             * Pseudo Accuracy
             * @enum {string}
             */
            readonly pseudo_accuracy: "efficiency" | "precision";
            /** Task */
            readonly task: string;
        };
        /** SerializedInputArtifact */
        readonly SerializedInputArtifact: {
            /** Media Type */
            readonly media_type: string | null;
            /** Path */
            readonly path: string;
            readonly provenance: components["schemas"]["Provenance"] | null;
            /** Role */
            readonly role: string;
            /** Sha256 */
            readonly sha256: string;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Source */
            readonly source: components["schemas"]["GeneratedArtifactSource"] | components["schemas"]["InstalledArtifactSource"];
        };
        /** SerializedModel */
        readonly SerializedModel: {
            /** Citation */
            readonly citation: string | null;
            /** Feature Set */
            readonly feature_set: string;
            /** Licence */
            readonly licence: string | null;
            /**
             * Model Type
             * @enum {string}
             */
            readonly model_type: "random_forest" | "cgcnn" | "xgboost";
            /** Name */
            readonly name: string;
            /** Revision */
            readonly revision: string | null;
            /**
             * Source
             * @enum {string}
             */
            readonly source: "huggingface" | "local";
            /** Target */
            readonly target: string;
            /** Version */
            readonly version: string;
        };
        /** SerializedPseudoMetadata */
        readonly SerializedPseudoMetadata: {
            /** Accuracy */
            readonly accuracy: ("efficiency" | "precision") | null;
            /** Content Sha256 */
            readonly content_sha256: string | null;
            /** Content Size Bytes */
            readonly content_size_bytes: number | null;
            readonly cutoffs: components["schemas"]["PseudoCutoffs"] | null;
            /** Element */
            readonly element: string | null;
            /** Filename */
            readonly filename: string;
            /** Frozen 4F Core */
            readonly frozen_4f_core: boolean;
            /** Functional */
            readonly functional: string | null;
            /** Header Format */
            readonly header_format: string;
            /** Provider */
            readonly provider: string | null;
            /** Pseudo Type */
            readonly pseudo_type: ("NC" | "USPP" | "PAW") | null;
            /** Relativistic */
            readonly relativistic: ("scalar" | "full" | "non-relativistic") | null;
            /** Source Identifier */
            readonly source_identifier: string | null;
            /** Table Id */
            readonly table_id: string | null;
            /** Warnings */
            readonly warnings: readonly string[];
            /** Z Valence */
            readonly z_valence: number | null;
        };
        /** SerializedPseudopotentialSelection */
        readonly SerializedPseudopotentialSelection: {
            /** Ecutrho Ry */
            readonly ecutrho_ry: number | null;
            /** Ecutwfc Ry */
            readonly ecutwfc_ry: number | null;
            /** Element */
            readonly element: string;
            /** Filename */
            readonly filename: string | null;
            /** Functional */
            readonly functional: string | null;
            readonly provenance: components["schemas"]["Provenance"];
            /** Relativistic */
            readonly relativistic: ("scalar" | "full" | "non-relativistic") | null;
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** SerializedRuntime */
        readonly SerializedRuntime: {
            /** Assets */
            readonly assets: readonly components["schemas"]["SerializedRuntimeAsset"][];
            /** Core Version */
            readonly core_version: string;
            /** Models */
            readonly models: readonly components["schemas"]["SerializedModel"][];
        };
        /** SerializedRuntimeAsset */
        readonly SerializedRuntimeAsset: {
            /** Files */
            readonly files: readonly components["schemas"]["RuntimeAssetFile"][];
            /** Id */
            readonly id: string;
            readonly model: components["schemas"]["SerializedModel"];
            /** Preparation Fingerprint */
            readonly preparation_fingerprint: string;
            /** Role */
            readonly role: string;
            /** Version */
            readonly version: string;
        };
        /** SmearingAdvice */
        readonly SmearingAdvice: {
            readonly provenance: components["schemas"]["Provenance"];
            /** Smearing Type */
            readonly smearing_type: string | null;
            /** Width Ry */
            readonly width_ry: number | null;
        };
        /** SpeciesOccupancy */
        readonly SpeciesOccupancy: {
            /** Label */
            readonly label: string;
            /** Occupancy */
            readonly occupancy: number;
            /** Oxidation State */
            readonly oxidation_state?: number | null;
            /** Symbol */
            readonly symbol: string;
        };
        /** SpinOrbitAdvice */
        readonly SpinOrbitAdvice: {
            /** Consider */
            readonly consider: boolean;
            /** Enabled */
            readonly enabled: boolean;
            /** Heavy Elements */
            readonly heavy_elements: readonly string[];
            readonly provenance: components["schemas"]["Provenance"];
        };
        /** StageCapability */
        readonly StageCapability: {
            /** Description */
            readonly description: string;
            /** Id */
            readonly id: string;
            /** Input Record Ids */
            readonly input_record_ids: readonly string[];
            /** Name */
            readonly name: string;
            /** Output Record Id */
            readonly output_record_id: string;
        };
        /** StructureAnalysisRecord */
        readonly StructureAnalysisRecord: {
            /** Analysis Warnings */
            readonly analysis_warnings: readonly string[];
            /** Contains Actinides */
            readonly contains_actinides: boolean;
            /** Contains Heavy Elements */
            readonly contains_heavy_elements: boolean;
            /** Contains Lanthanides */
            readonly contains_lanthanides: boolean;
            /** Contains Transition Metals */
            readonly contains_transition_metals: boolean;
            /** Crystal System */
            readonly crystal_system: string | number | components["schemas"]["SymmetryUnavailable"] | null;
            /**
             * Dimensionality
             * @enum {string}
             */
            readonly dimensionality: "3d" | "2d" | "1d" | "molecule" | "unknown";
            /** Disorder Warnings */
            readonly disorder_warnings: readonly string[];
            /** Disordered Site Count */
            readonly disordered_site_count: number;
            /**
             * Electronic Character
             * @enum {string}
             */
            readonly electronic_character: "metal" | "insulator" | "likely_metal" | "unknown";
            /** Electronic Character Confidence */
            readonly electronic_character_confidence: number | null;
            /** Electronic Character Source */
            readonly electronic_character_source: string;
            /** Elements */
            readonly elements: readonly string[];
            /** Formula */
            readonly formula: string;
            /** Heavy Elements */
            readonly heavy_elements: readonly string[];
            /** Low Dimensional */
            readonly low_dimensional: boolean;
            /** Magnetic Elements */
            readonly magnetic_elements: readonly string[];
            /** Reduced Formula */
            readonly reduced_formula: string;
            /** Site Count */
            readonly site_count: number;
            /** Space Group Number */
            readonly space_group_number: string | number | components["schemas"]["SymmetryUnavailable"] | null;
            /** Space Group Symbol */
            readonly space_group_symbol: string | number | components["schemas"]["SymmetryUnavailable"] | null;
        };
        /** StructureDocument */
        readonly StructureDocument: {
            /** Formula */
            readonly formula: string;
            readonly lattice: components["schemas"]["LatticeDocument"];
            /** Periodicity */
            readonly periodicity: readonly [
                boolean,
                boolean,
                boolean
            ];
            /** Reduced Formula */
            readonly reduced_formula: string;
            /** Schema Version */
            readonly schema_version: number;
            /** Site Count */
            readonly site_count: number;
            /** Sites */
            readonly sites: readonly components["schemas"]["StructureSiteDocument"][];
        };
        /** StructureInspection */
        readonly StructureInspection: {
            /** Canonical Cif */
            readonly canonical_cif: string;
            /**
             * Schema Version
             * @default 1
             */
            readonly schema_version: number;
            readonly source: components["schemas"]["StructureSourceDocument"];
            readonly structure: components["schemas"]["StructureDocument"];
        };
        /** StructureInspectionRequest */
        readonly StructureInspectionRequest: {
            readonly source: components["schemas"]["InlineStructureSource"];
        };
        /** StructureSiteDocument */
        readonly StructureSiteDocument: {
            /** Cartesian Coordinates Angstrom */
            readonly cartesian_coordinates_angstrom: readonly [
                number,
                number,
                number
            ];
            /** Fractional Coordinates */
            readonly fractional_coordinates: readonly [
                number,
                number,
                number
            ];
            /** Species */
            readonly species: readonly components["schemas"]["SpeciesOccupancy"][];
        };
        /** StructureSourceDocument */
        readonly StructureSourceDocument: {
            /** Content */
            readonly content: string | null;
            /** Format */
            readonly format: string;
            /** Name */
            readonly name: string;
            /**
             * Origin
             * @enum {string}
             */
            readonly origin: "inline" | "path" | "generated";
            /** Sha256 */
            readonly sha256: string | null;
            /** Size Bytes */
            readonly size_bytes: number | null;
        };
        /** SymmetryUnavailable */
        readonly SymmetryUnavailable: {
            /** Reason */
            readonly reason: string;
        };
        /** VdwAdvice */
        readonly VdwAdvice: {
            /** Method */
            readonly method: ("d3" | "d3bj" | "ts" | "mbd") | null;
            readonly provenance: components["schemas"]["Provenance"];
            /** Use Vdw */
            readonly use_vdw: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly capabilities_capabilities_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    readonly compute_compute_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ComputeRequest"];
            };
        };
        readonly responses: {
            /** @description One reviewed Computation Result and its exact optional archive. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "multipart/form-data": components["schemas"]["PreparedComputation"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Failed Dependency */
            readonly 424: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly inspect_inspect_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StructureInspectionRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StructureInspection"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readonly ready_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
}
