"""Typed contracts for the staged Core recommendation pipeline."""

from __future__ import annotations

from goldilocks_core.contracts.protocols import KMeshAdvisor
from goldilocks_core.contracts.records import (
    BundleRecord,
    CalculationHints,
    CalculationIntent,
    ConvergenceAdvice,
    ConvergenceHints,
    CoreRecords,
    CoreResult,
    GeneratedFile,
    GeneratedFiles,
    KMeshEntry,
    KmeshHints,
    KPointSelection,
    MagnetismAdvice,
    ModelSpec,
    ParameterAdvice,
    PresetRequest,
    Provenance,
    PseudoHints,
    PseudopotentialAdvice,
    PseudopotentialSelection,
    QueryRequest,
    SelectionRecord,
    SmearingAdvice,
    SmearingHints,
    SpinHints,
    SpinOrbitAdvice,
    StructureAnalysisRecord,
    StructureFeatureVector,
    SymmetryUnavailable,
    VdwAdvice,
    VdwHints,
)
from goldilocks_core.contracts.serial import to_jsonable
from goldilocks_core.contracts.types import (
    CalcTask,
    CodeName,
    Dimensionality,
    ElectronicCharacter,
    JobMode,
    JsonDict,
    KPointGrid,
    KPointShift,
    ModelSource,
    ModelType,
    PathLike,
    ProvenanceSource,
    SmearingType,
    StructureInput,
    VdwMethod,
)

__all__ = [
    "BundleRecord",
    "CalcTask",
    "CalculationHints",
    "CalculationIntent",
    "CodeName",
    "ConvergenceAdvice",
    "ConvergenceHints",
    "CoreRecords",
    "CoreResult",
    "Dimensionality",
    "ElectronicCharacter",
    "GeneratedFile",
    "GeneratedFiles",
    "JobMode",
    "JsonDict",
    "KMeshAdvisor",
    "KMeshEntry",
    "KmeshHints",
    "KPointGrid",
    "KPointSelection",
    "KPointShift",
    "MagnetismAdvice",
    "ModelSource",
    "ModelSpec",
    "ModelType",
    "ParameterAdvice",
    "PathLike",
    "PresetRequest",
    "Provenance",
    "ProvenanceSource",
    "PseudoHints",
    "PseudopotentialAdvice",
    "PseudopotentialSelection",
    "QueryRequest",
    "SelectionRecord",
    "SmearingAdvice",
    "SmearingHints",
    "SmearingType",
    "SpinHints",
    "SpinOrbitAdvice",
    "StructureAnalysisRecord",
    "StructureFeatureVector",
    "StructureInput",
    "SymmetryUnavailable",
    "VdwAdvice",
    "VdwHints",
    "VdwMethod",
    "to_jsonable",
]
