from __future__ import annotations

from goldilocks_core.contracts.advice import (
    ConvergenceAdvice,
    MagnetismAdvice,
    ParameterAdvice,
    PseudopotentialRequirements,
    SmearingAdvice,
    SpinOrbitAdvice,
    VdwAdvice,
)
from goldilocks_core.contracts.analysis import (
    StructureAnalysisRecord,
    SymmetryUnavailable,
)
from goldilocks_core.contracts.hints import (
    CalculationHints,
    CalculationIntent,
    ConvergenceHints,
    KmeshHints,
    PseudoHints,
    SmearingHints,
    SpinHints,
    VdwHints,
)
from goldilocks_core.contracts.kpoints import KMeshEntry, KPointSelection
from goldilocks_core.contracts.models import ModelSpec, StructureFeatureVector
from goldilocks_core.contracts.outputs import (
    OUTPUT_RECORD_TYPES,
    OUTPUT_TYPES_BY_ID,
    resolve_output_types,
)
from goldilocks_core.contracts.protocols import KMeshAdvisor, KMeshService
from goldilocks_core.contracts.provenance import Provenance
from goldilocks_core.contracts.registry import RECORD_TYPE_IDS, record_type_id
from goldilocks_core.contracts.requests import (
    CalculationDraft,
    ComputationSelection,
    ComputeRequest,
    PresetSelection,
    RecordSelection,
)
from goldilocks_core.contracts.result import (
    BundleRecord,
    ComputationResult,
    GeneratedFile,
    GeneratedFiles,
    Publication,
    Records,
)
from goldilocks_core.contracts.selection import (
    PseudoCutoffs,
    PseudoMetadata,
    PseudopotentialSelection,
    SelectionRecord,
)
from goldilocks_core.contracts.serial import to_jsonable
from goldilocks_core.contracts.structure import (
    InlineStructureSource,
    InMemoryStructureSource,
    LatticeDocument,
    PathStructureSource,
    SpeciesOccupancy,
    StructureDocument,
    StructureFormat,
    StructureInspection,
    StructureSiteDocument,
    StructureSource,
    StructureSourceDocument,
)
from goldilocks_core.contracts.types import (
    CalcTask,
    CodeName,
    Dimensionality,
    ElectronicCharacter,
    JsonDict,
    KPointGrid,
    KPointShift,
    ModelSource,
    ModelType,
    PathLike,
    ProvenanceSource,
    PseudoAccuracy,
    PseudoType,
    RecordId,
    RelativisticTreatment,
    SmearingType,
    StageId,
    TaskId,
    VdwMethod,
)

__all__ = [
    "BundleRecord",
    "CalcTask",
    "CalculationDraft",
    "CalculationHints",
    "CalculationIntent",
    "CodeName",
    "ConvergenceAdvice",
    "ConvergenceHints",
    "ComputationResult",
    "ComputationSelection",
    "ComputeRequest",
    "Records",
    "Dimensionality",
    "ElectronicCharacter",
    "GeneratedFile",
    "GeneratedFiles",
    "InMemoryStructureSource",
    "InlineStructureSource",
    "JsonDict",
    "KMeshAdvisor",
    "KMeshEntry",
    "KmeshHints",
    "KMeshService",
    "KPointGrid",
    "LatticeDocument",
    "KPointSelection",
    "KPointShift",
    "MagnetismAdvice",
    "ModelSource",
    "ModelSpec",
    "ModelType",
    "OUTPUT_RECORD_TYPES",
    "OUTPUT_TYPES_BY_ID",
    "ParameterAdvice",
    "PathLike",
    "PathStructureSource",
    "PresetSelection",
    "Provenance",
    "Publication",
    "ProvenanceSource",
    "PseudoAccuracy",
    "PseudoCutoffs",
    "PseudoHints",
    "PseudoMetadata",
    "PseudoType",
    "PseudopotentialRequirements",
    "PseudopotentialSelection",
    "RecordSelection",
    "RECORD_TYPE_IDS",
    "RecordId",
    "RelativisticTreatment",
    "SelectionRecord",
    "SmearingAdvice",
    "SmearingHints",
    "SmearingType",
    "SpinHints",
    "SpinOrbitAdvice",
    "StageId",
    "SpeciesOccupancy",
    "StructureAnalysisRecord",
    "StructureFeatureVector",
    "StructureDocument",
    "StructureFormat",
    "StructureInspection",
    "StructureSiteDocument",
    "StructureSource",
    "StructureSourceDocument",
    "SymmetryUnavailable",
    "TaskId",
    "VdwAdvice",
    "VdwHints",
    "VdwMethod",
    "record_type_id",
    "resolve_output_types",
    "to_jsonable",
]
