"""Typed contracts for the staged Core recommendation pipeline."""

from __future__ import annotations

from goldilocks_core.contracts.protocols import (
    AdviseStage,
    AnalyzeStage,
    BundleStage,
    GenerateStage,
    KMeshAdvisor,
    SelectStage,
)
from goldilocks_core.contracts.records import (
    BundleRecord,
    CalculationHints,
    CalculationIntent,
    ConvergenceAdvice,
    CoreJobRequest,
    CoreResult,
    GeneratedFile,
    KMeshEntry,
    KPointAdvice,
    KPointSelection,
    MagnetismAdvice,
    ModelSpec,
    ParameterAdvice,
    Provenance,
    PseudopotentialAdvice,
    PseudopotentialSelection,
    SelectionRecord,
    SmearingAdvice,
    SpinOrbitAdvice,
    StructureAnalysisRecord,
    StructureFeatureVector,
    VdwAdvice,
)
from goldilocks_core.contracts.serial import to_jsonable
from goldilocks_core.contracts.types import (
    CalcTask,
    CodeName,
    Dimensionality,
    ElectronicCharacter,
    JobMode,
    JsonDict,
    KPointGrid,
    KPointShift,
    ModelSource,
    ModelType,
    PathLike,
    ProvenanceSource,
    SmearingType,
    StructureInput,
    VdwMethod,
)

__all__ = [
    "AdviseStage",
    "AnalyzeStage",
    "BundleRecord",
    "BundleStage",
    "CalcTask",
    "CalculationHints",
    "CalculationIntent",
    "CodeName",
    "ConvergenceAdvice",
    "CoreJobRequest",
    "CoreResult",
    "Dimensionality",
    "ElectronicCharacter",
    "GenerateStage",
    "GeneratedFile",
    "JobMode",
    "JsonDict",
    "KMeshAdvisor",
    "KMeshEntry",
    "KPointAdvice",
    "KPointGrid",
    "KPointSelection",
    "KPointShift",
    "MagnetismAdvice",
    "ModelSource",
    "ModelSpec",
    "ModelType",
    "ParameterAdvice",
    "PathLike",
    "Provenance",
    "ProvenanceSource",
    "PseudopotentialAdvice",
    "PseudopotentialSelection",
    "SelectStage",
    "SelectionRecord",
    "SmearingAdvice",
    "SmearingType",
    "SpinOrbitAdvice",
    "StructureAnalysisRecord",
    "StructureFeatureVector",
    "StructureInput",
    "VdwAdvice",
    "VdwMethod",
    "to_jsonable",
]
